server:
  port: 5006
spring:
  application:
    name: API-GATEWAY-BILLING
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
      routes:
        - id: kenya_route
          uri: http://192.168.48.25:5001/
          predicates:
            - Path=/api/kenya/**
        - id: orange_burkina_route
          uri: http://192.168.48.25:5001/
          predicates:
            - Path=/api/orange-burkina/**
        - id: zain_iraq_route
          uri: http://192.168.48.25:5001/
          predicates:
            - Path=/api/zain-iraq/**
        - id: ksa_route
          uri: http://192.168.48.25:5001/
          predicates:
            - Path=/api/ksa/**
         
eureka:       
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url:
      defaultZone: http://192.168.48.25:5005/eureka    